/* eslint-disable no-unused-vars */
const C = {
  empty: () => ({ t: 'empty' }),
  cmt: s => ({ t: 'cmt', s }),
  code: s => ({ t: 'code', s })
};

function buildProjectFile(slug, lang) {
  const p = PROJECTS_DATA[slug][lang];
  const cls = p.name.replace(/[^a-zA-Z]/g, '') || 'Project';
  const lines = [
    C.cmt(`# app/models/projects/${PROJECTS_DATA[slug].slug}.rb`),
    C.empty(),
    C.code(`<kw>class</kw> <cls>${cls}</cls> < <cls>Project</cls>`),
    C.code(`  <ann># @role</ann>     <str>"${p.role}"</str>`),
    C.code(`  <ann># @stack</ann>    <str>"${p.skills}"</str>`),
    C.empty(),
    C.code(`  <kw>def</kw> <mth>description</mth>`),
    C.code(`    <str>"${p.description}"</str>`),
    C.code(`  <kw>end</kw>`),
    C.empty(),
    C.code(`  <kw>def</kw> <mth>achievements</mth>`),
    C.code(`    <sym>[</sym>`)
  ];
  p.achievements.forEach((a, i) => {
    const comma = i < p.achievements.length - 1 ? ',' : '';
    lines.push(C.code(`      <str>"${a}"</str>${comma}`));
  });
  lines.push(C.code(`    <sym>]</sym>`));
  lines.push(C.code(`  <kw>end</kw>`));
  lines.push(C.code(`<kw>end</kw>`));
  return lines;
}

const CODE_FILES = {
  resume: {
    en: [
      C.cmt('# dubrounik.resume.rb'),
      C.cmt('# Senior Software Engineer · 8+ years · Grodno, Belarus'),
      C.cmt('# "Code is poetry. Ruby is the language of it."'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Dubrounik</cls> < <cls>ApplicationRecord</cls>'),
      C.code('  <ann># @author</ann> <str>"Artsiom Dubrounik"</str>'),
      C.code('  <ann># @photo</ann> <str>"assets/photo.jpg"</str>'),
      C.code('  <ann># @role</ann>    <str>"Senior Software Engineer"</str>'),
      C.code('  <ann># @since</ann>   <num>2016</num>'),
      C.code('  <ann># @github</ann>  <str>"fooooxmr"</str>'),
      C.code('  <ann># @stack</ann>   <sym>%i</sym>[<r1>:ruby</r1>, <r2>:rails</r2>, <r3>:react</r3>, <r4>:aws</r4>]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>about_me</mth>'),
      C.code('    <str><<~BIO</str>'),
      C.code('      Software engineer with 8+ years across the full SDLC:'),
      C.code('      OO analysis & design, implementation, testing, deployment, support.'),
      C.code('      Strong analytical skills. OOP expert. Agile/XP practitioner.'),
      C.code('      Effective team player — delivers on time and within budget.'),
      C.code('      Constantly learns new technologies. Large-scale project experience.'),
      C.code('      Ruby developer & teacher. Mentoring via pair programming.'),
      C.code('      AI-driven code generation: Copilot, Cursor — high-quality codebases.'),
      C.code('      Team Manager @ iTechArt · Founder @ The Lessoner · Mentor @ IT Academy.'),
      C.code('    <str>BIO</str>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>core_competencies</mth>'),
      C.code('    <sym>{</sym>'),
      C.code('      languages:  <sym>%i</sym>[<r1>ruby</r1> <r2>javascript</r2> <r3>java</r3> <r4>html_scss</r4>],'),
      C.code('      frameworks: <sym>%i</sym>[<r1>rails</r1> <r2>react</r2> <r3>rspec</r3> <r4>cucumber</r4>],'),
      C.code('      infra:      <sym>%i</sym>[<r1>aws</r1> <r2>docker</r2> <r3>kubernetes</r3> <r4>heroku</r4>],'),
      C.code('      data:       <sym>%i</sym>[<r1>postgresql</r1> <r2>mysql</r2> <r3>redis</r3> <r4>redshift</r4>],'),
      C.code('      messaging:  <sym>%i</sym>[<r1>sidekiq</r1> <r2>sqs</r2> <r3>shoryuken</r3> <r4>rabbitmq</r4>],'),
      C.code('      auth:       <sym>%i</sym>[<r1>saml</r1> <r2>auth0</r2> <r3>okta</r3> <r4>ldap</r4>],'),
      C.code('      ai:         <sym>%i</sym>[<r1>copilot</r1> <r2>cursor</r2> <r3>codegen</r3>]'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>current_positions</mth>'),
      C.code('    <sym>[</sym>'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Team Manager"</str>, <str>"iTechArt Group"</str>, <kw>since:</kw> <num>2018</num>),'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Education Mentor"</str>, <str>"IT Academy Grodno"</str>, <kw>since:</kw> <num>2021</num>),'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Founder"</str>, <str>"The Lessoner"</str>, <kw>since:</kw> <num>2022</num>)'),
      C.code('    <sym>]</sym>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>hire!</mth>  <cmt># ← set breakpoint here</cmt>'),
      C.code('    <cls>ContactController</cls>.<mth>reach_out</mth>(<str>"artsiom.dubrounik@gmail.com"</str>)'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# dubrounik.resume.rb'),
      C.cmt('# Senior Software Engineer · 8+ лет · Гродно, Беларусь'),
      C.cmt('# «Код — это поэзия. Ruby — её язык.»'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Дубровник</cls> < <cls>ApplicationRecord</cls>'),
      C.code('  <ann># @автор</ann>  <str>"Артём Дубровник"</str>'),
      C.code('  <ann># @фото</ann>   <str>"assets/photo.jpg"</str>'),
      C.code('  <ann># @роль</ann>   <str>"Senior Software Engineer"</str>'),
      C.code('  <ann># @с</ann>      <num>2016</num>'),
      C.code('  <ann># @github</ann> <str>"fooooxmr"</str>'),
      C.code('  <ann># @стек</ann>   <sym>%i</sym>[<r1>:ruby</r1>, <r2>:rails</r2>, <r3>:react</r3>, <r4>:aws</r4>]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>о_себе</mth>'),
      C.code('    <str><<~BIO</str>'),
      C.code('      Инженер с 8+ годами во всём цикле разработки:'),
      C.code('      ОО-анализ, проектирование, реализация, тестирование, деплой, поддержка.'),
      C.code('      Сильные аналитические навыки. Эксперт в ООП. Agile/XP.'),
      C.code('      Эффективный командный игрок — в срок и в бюджет.'),
      C.code('      Постоянно изучает новые технологии. Опыт крупных проектов.'),
      C.code('      Ruby-разработчик и преподаватель. Менторинг через pair programming.'),
      C.code('      AI-генерация кода: Copilot, Cursor — качественные кодовые базы.'),
      C.code('      Team Manager @ iTechArt · Основатель The Lessoner · Ментор IT Academy.'),
      C.code('    <str>BIO</str>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>ключевые_компетенции</mth>'),
      C.code('    <sym>{</sym>'),
      C.code('      языки:      <sym>%i</sym>[<r1>ruby</r1> <r2>javascript</r2> <r3>java</r3> <r4>html_scss</r4>],'),
      C.code('      фреймворки: <sym>%i</sym>[<r1>rails</r1> <r2>react</r2> <r3>rspec</r3> <r4>cucumber</r4>],'),
      C.code('      инфра:      <sym>%i</sym>[<r1>aws</r1> <r2>docker</r2> <r3>kubernetes</r3> <r4>heroku</r4>],'),
      C.code('      данные:     <sym>%i</sym>[<r1>postgresql</r1> <r2>mysql</r2> <r3>redis</r3> <r4>redshift</r4>],'),
      C.code('      очереди:    <sym>%i</sym>[<r1>sidekiq</r1> <r2>sqs</r2> <r3>shoryuken</r3> <r4>rabbitmq</r4>],'),
      C.code('      auth:       <sym>%i</sym>[<r1>saml</r1> <r2>auth0</r2> <r3>okta</r3> <r4>ldap</r4>],'),
      C.code('      ai:         <sym>%i</sym>[<r1>copilot</r1> <r2>cursor</r2> <r3>codegen</r3>]'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>текущие_позиции</mth>'),
      C.code('    <sym>[</sym>'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Team Manager"</str>, <str>"iTechArt Group"</str>, <kw>с:</kw> <num>2018</num>),'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Ментор"</str>, <str>"IT Academy"</str>, <kw>с:</kw> <num>2021</num>),'),
      C.code('      <cls>Position</cls>.<mth>new</mth>(<str>"Основатель"</str>, <str>"The Lessoner"</str>, <kw>с:</kw> <num>2022</num>)'),
      C.code('    <sym>]</sym>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>нанять!</mth>  <cmt># ← точка останова</cmt>'),
      C.code('    <cls>ContactController</cls>.<mth>связаться</mth>(<str>"artsiom.dubrounik@gmail.com"</str>)'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  experience: {
    en: [
      C.cmt('# app/models/experience.rb'),
      C.empty(),
      C.code('<kw>module</kw> <cls>Experience</cls>'),
      C.code('  ROLES = <sym>[</sym>'),
      C.code('    <sym>{</sym> title: <str>"Team Manager"</str>, company: <str>"iTechArt Group"</str>, period: <str>"2018–present"</str>,'),
      C.code('      duties: <str>"Technical growth, architecture, hiring, mentoring"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Education Mentor"</str>, company: <str>"IT Academy Grodno"</str>, period: <str>"2021–present"</str>,'),
      C.code('      duties: <str>"Curriculum, pair programming sessions, code reviews"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Founder"</str>, company: <str>"The Lessoner"</str>, period: <str>"2022–present"</str>,'),
      C.code('      duties: <str>"Nonprofit IT education for Grodno community"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Senior Ruby Developer"</str>, company: <str>"Anadea"</str>, period: <str>"2018"</str>,'),
      C.code('      duties: <str>"Tracker PM tool, agile collaboration platform"</str> <sym>}</sym>'),
      C.code('  <sym>]</sym>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.total_years</mth>'),
      C.code('    <num>8</num>.<mth>years</mth> + <num>2</num>.<mth>months</mth>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.highlights</mth>'),
      C.code('    <sym>[</sym>'),
      C.code('      <str>"Led technical growth of engineering teams"</str>,'),
      C.code('      <str>"Mentoring through pair programming"</str>,'),
      C.code('      <str>"AI-driven code generation & workflow optimization"</str>,'),
      C.code('      <str>"Architecture for 9 enterprise projects"</str>,'),
      C.code('      <str>"Sidekiq ↔ SQS migrations both directions"</str>,'),
      C.code('      <str>"SSO/SAML for millions of users"</str>,'),
      C.code('      <str>"Rails 3→6 migration with 85% test coverage"</str>,'),
      C.code('      <str>"Founded nonprofit IT education initiative"</str>'),
      C.code('    <sym>]</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# app/models/experience.rb'),
      C.empty(),
      C.code('<kw>module</kw> <cls>Experience</cls>'),
      C.code('  ROLES = <sym>[</sym>'),
      C.code('    <sym>{</sym> title: <str>"Team Manager"</str>, company: <str>"iTechArt Group"</str>, period: <str>"2018–н.в."</str>,'),
      C.code('      duties: <str>"Техрост команды, архитектура, найм, менторинг"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Ментор"</str>, company: <str>"IT Academy Гродно"</str>, period: <str>"2021–н.в."</str>,'),
      C.code('      duties: <str>"Программа, pair programming, code review"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Основатель"</str>, company: <str>"The Lessoner"</str>, period: <str>"2022–н.в."</str>,'),
      C.code('      duties: <str>"Некоммерческое IT-образование в Гродно"</str> <sym>}</sym>,'),
      C.code('    <sym>{</sym> title: <str>"Ruby Developer"</str>, company: <str>"Anadea"</str>, period: <str>"2018"</str>,'),
      C.code('      duties: <str>"Tracker — agile PM платформа"</str> <sym>}</sym>'),
      C.code('  <sym>]</sym>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.total_years</mth>'),
      C.code('    <num>8</num>.<mth>years</mth> + <num>2</num>.<mth>months</mth>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.highlights</mth>'),
      C.code('    <sym>[</sym>'),
      C.code('      <str>"Технический рост инженерных команд"</str>,'),
      C.code('      <str>"Менторинг через pair programming"</str>,'),
      C.code('      <str>"AI-генерация кода и оптимизация процессов"</str>,'),
      C.code('      <str>"Архитектура для 9 enterprise-проектов"</str>,'),
      C.code('      <str>"Миграции Sidekiq ↔ SQS в обе стороны"</str>,'),
      C.code('      <str>"SSO/SAML для миллионов пользователей"</str>,'),
      C.code('      <str>"Миграция Rails 3→6, 85% покрытие тестами"</str>,'),
      C.code('      <str>"Основал некоммерческий IT-образовательный проект"</str>'),
      C.code('    <sym>]</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  education: {
    en: [
      C.cmt('# app/models/education.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Education</cls>'),
      C.code('  DEGREE = <sym>{</sym>'),
      C.code('    university: <str>"Yanka Kupala State University of Grodno"</str>,'),
      C.code('    faculty:    <str>"Software Development"</str>,'),
      C.code('    period:     <str>"2014–2018"</str>,'),
      C.code('    hobbies:    <sym>%i</sym>[<r1>teaching</r1> <r2>psychology</r2> <r3>mentoring</r3>]'),
      C.code('  <sym>}</sym>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.mentoring_philosophy</mth>'),
      C.code('    <str>"Simplify complex concepts. Empower learners. Pair program to excellence."</str>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# app/models/education.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Education</cls>'),
      C.code('  DEGREE = <sym>{</sym>'),
      C.code('    university: <str>"ГрГУ им. Янки Купалы"</str>,'),
      C.code('    faculty:    <str>"Разработка программного обеспечения"</str>,'),
      C.code('    period:     <str>"2014–2018"</str>,'),
      C.code('    hobbies:    <sym>%i</sym>[<r1>преподавание</r1> <r2>психология</r2> <r3>менторинг</r3>]'),
      C.code('  <sym>}</sym>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.mentoring_philosophy</mth>'),
      C.code('    <str>"Упрощать сложное. Вдохновлять учеников. Pair programming до excellence."</str>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  projects: {
    en: [
      C.cmt('# app/models/projects.rb — registry of 9 major projects'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Projects</cls>'),
      C.code('  <ann># Open individual files in app/models/projects/</ann>'),
      C.code('  REGISTRY = <sym>%i</sym>['),
      ...PROJECT_KEYS.map((k, i) => C.code(`    <sym>:</sym><r1>${k}</r1>${i < PROJECT_KEYS.length - 1 ? ',' : ''}`)),
      C.code('  ]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.all</mth>'),
      C.code('    REGISTRY.map <sym>{</sym> <sym>|</sym>key<sym>|</sym> <cls>Project</cls>.<mth>load</mth>(key) <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>def</kw> <mth>self.count</mth>'),
      C.code('    <num>9</num>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# app/models/projects.rb — реестр 9 крупных проектов'),
      C.empty(),
      C.code('<kw>class</kw> <cls>Projects</cls>'),
      C.code('  <ann># Откройте файлы в app/models/projects/</ann>'),
      C.code('  REGISTRY = <sym>%i</sym>['),
      ...PROJECT_KEYS.map((k, i) => C.code(`    <sym>:</sym><r1>${k}</r1>${i < PROJECT_KEYS.length - 1 ? ',' : ''}`)),
      C.code('  ]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.all</mth>'),
      C.code('    REGISTRY.map <sym>{</sym> <sym>|</sym>key<sym>|</sym> <cls>Project</cls>.<mth>load</mth>(key) <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>def</kw> <mth>self.count</mth>'),
      C.code('    <num>9</num>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  skills: {
    en: [
      C.cmt('# app/services/skills_engine.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>SkillsEngine</cls>'),
      C.code('  OS = <sym>%i</sym>[linux macos windows]'),
      C.code('  PM_TOOLS = <sym>%i</sym>[jira trello myhours shortcut]'),
      C.code('  VCS = <sym>%i</sym>[github gitlab]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>evaluate</mth>'),
      C.code('    <sym>{</sym>'),
      C.code('      <str>"Ruby on Rails"</str>  => <sym>:expert</sym>,'),
      C.code('      <str>"Ruby"</str>           => <sym>:expert</sym>,'),
      C.code('      <str>"PostgreSQL"</str>     => <sym>:expert</sym>,'),
      C.code('      <str>"React"</str>          => <sym>:advanced</sym>,'),
      C.code('      <str>"AWS"</str>            => <sym>:advanced</sym>,'),
      C.code('      <str>"Docker/K8s"</str>     => <sym>:advanced</sym>,'),
      C.code('      <str>"Redis/Sidekiq"</str>  => <sym>:expert</sym>,'),
      C.code('      <str>"Microservices"</str>  => <sym>:advanced</sym>,'),
      C.code('      <str>"SAML/Auth0/Okta"</str>=> <sym>:advanced</sym>,'),
      C.code('      <str>"RSpec/Cucumber"</str> => <sym>:expert</sym>,'),
      C.code('      <str>"AI Tooling"</str>     => <sym>:advanced</sym>,'),
      C.code('      <str>"Team Leadership"</str>=> <sym>:expert</sym>,'),
      C.code('      <str>"Mentoring"</str>      => <sym>:expert</sym>'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# app/services/skills_engine.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>SkillsEngine</cls>'),
      C.code('  OS = <sym>%i</sym>[linux macos windows]'),
      C.code('  PM_TOOLS = <sym>%i</sym>[jira trello myhours shortcut]'),
      C.code('  VCS = <sym>%i</sym>[github gitlab]'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>evaluate</mth>'),
      C.code('    <sym>{</sym>'),
      C.code('      <str>"Ruby on Rails"</str>  => <sym>:expert</sym>,'),
      C.code('      <str>"Ruby"</str>           => <sym>:expert</sym>,'),
      C.code('      <str>"PostgreSQL"</str>     => <sym>:expert</sym>,'),
      C.code('      <str>"React"</str>          => <sym>:advanced</sym>,'),
      C.code('      <str>"AWS"</str>            => <sym>:advanced</sym>,'),
      C.code('      <str>"Docker/K8s"</str>     => <sym>:advanced</sym>,'),
      C.code('      <str>"Redis/Sidekiq"</str>  => <sym>:expert</sym>,'),
      C.code('      <str>"Микросервисы"</str>   => <sym>:advanced</sym>,'),
      C.code('      <str>"SAML/Auth0/Okta"</str>=> <sym>:advanced</sym>,'),
      C.code('      <str>"RSpec/Cucumber"</str> => <sym>:expert</sym>,'),
      C.code('      <str>"AI-инструменты"</str> => <sym>:advanced</sym>,'),
      C.code('      <str>"Лидерство"</str>      => <sym>:expert</sym>,'),
      C.code('      <str>"Менторинг"</str>      => <sym>:expert</sym>'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  readme: {
    en: [
      C.cmt('# README.md'),
      C.cmt('# dubrounik.resume'),
      C.empty(),
      C.code('<str>## Artsiom Dubrounik</str>'),
      C.code('<str>Senior Software Engineer · Ruby on Rails · 8+ years</str>'),
      C.empty(),
      C.code('<str>Interactive resume styled as RubyMine IDE.</str>'),
      C.code('<str>Explore the project tree, run specs, debug breakpoints,</str>'),
      C.code('<str>or type `irb` in the terminal for a live Ruby console.</str>'),
      C.empty(),
      C.code('<str>## Quick start</str>'),
      C.code('<str>```bash</str>'),
      C.code('<str>bundle install</str>'),
      C.code('<str>ruby dubrounik.resume.rb</str>'),
      C.code('<str>bundle exec rspec</str>'),
      C.code('<str>irb -r ./dubrounik.resume.rb</str>'),
      C.code('<str>```</str>'),
      C.empty(),
      C.code('<str>## Structure</str>'),
      C.code('<str>- `dubrounik.resume.rb` — main profile</str>'),
      C.code('<str>- `app/models/projects/` — 9 detailed project files</str>'),
      C.code('<str>- `app/services/skills_engine.rb` — tech stack</str>'),
      C.code('<str>- `Gemfile` — dependencies & gems</str>'),
      C.empty(),
      C.code('<str>## Contact</str>'),
      C.code('<str>artsiom.dubrounik@gmail.com</str>'),
      C.code('<str>linkedin.com/in/artsiom-dubrounik-813750146</str>'),
      C.code('<str>github.com/fooooxmr</str>')
    ],
    ru: [
      C.cmt('# README.md'),
      C.cmt('# dubrounik.resume'),
      C.empty(),
      C.code('<str>## Артём Дубровник</str>'),
      C.code('<str>Senior Software Engineer · Ruby on Rails · 8+ лет</str>'),
      C.empty(),
      C.code('<str>Интерактивное резюме в стиле RubyMine IDE.</str>'),
      C.code('<str>Изучайте дерево проекта, запускайте тесты, ставьте breakpoints,</str>'),
      C.code('<str>или введите `irb` в терминале для живой Ruby-консоли.</str>'),
      C.empty(),
      C.code('<str>## Быстрый старт</str>'),
      C.code('<str>```bash</str>'),
      C.code('<str>bundle install</str>'),
      C.code('<str>ruby dubrounik.resume.rb</str>'),
      C.code('<str>bundle exec rspec</str>'),
      C.code('<str>irb -r ./dubrounik.resume.rb</str>'),
      C.code('<str>```</str>'),
      C.empty(),
      C.code('<str>## Структура</str>'),
      C.code('<str>- `dubrounik.resume.rb` — основной профиль</str>'),
      C.code('<str>- `app/models/projects/` — 9 файлов проектов</str>'),
      C.code('<str>- `app/services/skills_engine.rb` — стек технологий</str>'),
      C.code('<str>- `Gemfile` — зависимости и гемы</str>'),
      C.empty(),
      C.code('<str>## Контакты</str>'),
      C.code('<str>artsiom.dubrounik@gmail.com</str>'),
      C.code('<str>linkedin.com/in/artsiom-dubrounik-813750146</str>'),
      C.code('<str>github.com/fooooxmr</str>')
    ]
  },
  gemfile: {
    en: [
      C.cmt('# Gemfile'),
      C.cmt('# dubrounik.resume dependencies'),
      C.empty(),
      C.code('<kw>source</kw> <str>"https://rubygems.org"</str>'),
      C.empty(),
      C.code('<kw>gem</kw> <str>"rails"</str>, <str>"~> 8.0"</str>'),
      C.code('<kw>gem</kw> <str>"ruby"</str>, <str>"~> 3.3"</str>'),
      C.code('<kw>gem</kw> <str>"pg"</str>'),
      C.code('<kw>gem</kw> <str>"redis"</str>'),
      C.code('<kw>gem</kw> <str>"sidekiq"</str>'),
      C.code('<kw>gem</kw> <str>"shoryuken"</str>'),
      C.code('<kw>gem</kw> <str>"react-rails"</str>'),
      C.code('<kw>gem</kw> <str>"rspec-rails"</str>'),
      C.code('<kw>gem</kw> <str>"cucumber-rails"</str>'),
      C.code('<kw>gem</kw> <str>"devise"</str>'),
      C.code('<kw>gem</kw> <str>"omniauth-auth0"</str>'),
      C.code('<kw>gem</kw> <str>"ruby-saml"</str>'),
      C.code('<kw>gem</kw> <str>"aws-sdk-s3"</str>'),
      C.code('<kw>gem</kw> <str>"aws-sdk-sqs"</str>'),
      C.code('<kw>gem</kw> <str>"elasticsearch-model"</str>'),
      C.code('<kw>gem</kw> <str>"twilio-ruby"</str>'),
      C.code('<kw>gem</kw> <str>"grape"</str>'),
      C.code('<kw>gem</kw> <str>"puma"</str>'),
      C.code('<kw>gem</kw> <str>"rubocop"</str>, <kw>group:</kw> <sym>:development</sym>'),
      C.empty(),
      C.code('<cmt># bundle install && bundle exec dubrounik --hire</cmt>')
    ],
    ru: [
      C.cmt('# Gemfile'),
      C.cmt('# зависимости dubrounik.resume'),
      C.empty(),
      C.code('<kw>source</kw> <str>"https://rubygems.org"</str>'),
      C.empty(),
      C.code('<kw>gem</kw> <str>"rails"</str>, <str>"~> 8.0"</str>'),
      C.code('<kw>gem</kw> <str>"ruby"</str>, <str>"~> 3.3"</str>'),
      C.code('<kw>gem</kw> <str>"pg"</str>'),
      C.code('<kw>gem</kw> <str>"redis"</str>'),
      C.code('<kw>gem</kw> <str>"sidekiq"</str>'),
      C.code('<kw>gem</kw> <str>"shoryuken"</str>'),
      C.code('<kw>gem</kw> <str>"react-rails"</str>'),
      C.code('<kw>gem</kw> <str>"rspec-rails"</str>'),
      C.code('<kw>gem</kw> <str>"cucumber-rails"</str>'),
      C.code('<kw>gem</kw> <str>"devise"</str>'),
      C.code('<kw>gem</kw> <str>"omniauth-auth0"</str>'),
      C.code('<kw>gem</kw> <str>"ruby-saml"</str>'),
      C.code('<kw>gem</kw> <str>"aws-sdk-s3"</str>'),
      C.code('<kw>gem</kw> <str>"aws-sdk-sqs"</str>'),
      C.code('<kw>gem</kw> <str>"elasticsearch-model"</str>'),
      C.code('<kw>gem</kw> <str>"twilio-ruby"</str>'),
      C.code('<kw>gem</kw> <str>"grape"</str>'),
      C.code('<kw>gem</kw> <str>"puma"</str>'),
      C.code('<kw>gem</kw> <str>"rubocop"</str>, <kw>group:</kw> <sym>:development</sym>'),
      C.empty(),
      C.code('<cmt># bundle install && bundle exec dubrounik --hire</cmt>')
    ]
  },
  contact: {
    en: [
      C.cmt('# app/controllers/contact_controller.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>ContactController</cls> < <cls>ApplicationController</cls>'),
      C.code('  <kw>def</kw> <mth>hire</mth>'),
      C.code('    <mth>reach_out</mth> <cmt># you are here</cmt>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.reach_out</mth>(email)'),
      C.code('    <sym>{</sym>'),
      C.code('      name:     <str>"Artsiom Dubrounik"</str>,'),
      C.code('      email:    <str>"artsiom.dubrounik@gmail.com"</str>,'),
      C.code('      linkedin: <str>"linkedin.com/in/artsiom-dubrounik-813750146"</str>,'),
      C.code('      github:   <str>"github.com/fooooxmr"</str>,'),
      C.code('      location: <str>"Grodno, Belarus — Remote OK"</str>,'),
      C.code('      photo:    <str>"assets/photo.jpg"</str>'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# app/controllers/contact_controller.rb'),
      C.empty(),
      C.code('<kw>class</kw> <cls>ContactController</cls> < <cls>ApplicationController</cls>'),
      C.code('  <kw>def</kw> <mth>hire</mth>'),
      C.code('    <mth>reach_out</mth> <cmt># вы здесь</cmt>'),
      C.code('  <kw>end</kw>'),
      C.empty(),
      C.code('  <kw>def</kw> <mth>self.reach_out</mth>(email)'),
      C.code('    <sym>{</sym>'),
      C.code('      name:     <str>"Артём Дубровник"</str>,'),
      C.code('      email:    <str>"artsiom.dubrounik@gmail.com"</str>,'),
      C.code('      linkedin: <str>"linkedin.com/in/artsiom-dubrounik-813750146"</str>,'),
      C.code('      github:   <str>"github.com/fooooxmr"</str>,'),
      C.code('      location: <str>"Гродно, Беларусь — Удалённо"</str>,'),
      C.code('      photo:    <str>"assets/photo.jpg"</str>'),
      C.code('    <sym>}</sym>'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  spec: {
    en: [
      C.cmt('# spec/achievements_spec.rb'),
      C.empty(),
      C.code('<kw>describe</kw> <cls>Dubrounik</cls> <kw>do</kw>'),
      C.code('  <kw>it</kw> <str>"migrates Sidekiq to SQS and back flawlessly"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>handle_queue_migration</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"implements SSO for millions of learners"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>integrate_saml</mth>(:avallain)'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"fixes memory leaks under pressure"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>profile_and_optimize</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"mentors juniors to excellence"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>pair_program</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"migrates Rails 3 to 6 with 85% coverage"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>upgrade_rails</mth>(<num>3</num>, <num>6</num>)'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ],
    ru: [
      C.cmt('# spec/achievements_spec.rb'),
      C.empty(),
      C.code('<kw>describe</kw> <cls>Дубровник</cls> <kw>do</kw>'),
      C.code('  <kw>it</kw> <str>"мигрирует Sidekiq ↔ SQS без потерь"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>handle_queue_migration</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"внедряет SSO для миллионов"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>integrate_saml</mth>(:avallain)'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"чинит утечки памяти под нагрузкой"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>profile_and_optimize</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"выводит джунов на excellence"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>pair_program</mth>'),
      C.code('  <kw>end</kw>'),
      C.code('  <kw>it</kw> <str>"мигрирует Rails 3→6 с 85% покрытием"</str> <kw>do</kw>'),
      C.code('    <mth>expect</mth>(subject).<mth>to</mth> <mth>upgrade_rails</mth>(<num>3</num>, <num>6</num>)'),
      C.code('  <kw>end</kw>'),
      C.code('<kw>end</kw>')
    ]
  },
  photo: {
    en: [
      C.cmt('# assets/photo.jpg'),
      C.cmt('# @author Artsiom Dubrounik'),
      C.empty(),
      C.code('<str># Profile photo — GitHub @fooooxmr</str>'),
      C.code('<str># Click "Hire" or set breakpoint on hire! to connect</str>')
    ],
    ru: [
      C.cmt('# assets/photo.jpg'),
      C.cmt('# @автор Артём Дубровник'),
      C.empty(),
      C.code('<str># Фото профиля — GitHub @fooooxmr</str>'),
      C.code('<str># Нажмите Hire или breakpoint на нанять! для связи</str>')
    ]
  }
};

PROJECT_KEYS.forEach(slug => {
  const key = PROJECTS_DATA[slug].key;
  CODE_FILES[key] = { en: buildProjectFile(slug, 'en'), ru: buildProjectFile(slug, 'ru') };
});

const FILE_KEYS = {
  resume: 'files.resume',
  experience: 'files.experience',
  education: 'files.education',
  skills: 'files.skills',
  projects: 'files.projects',
  contact: 'files.contact',
  spec: 'files.spec',
  readme: 'files.readme',
  gemfile: 'files.gemfile',
  photo: 'files.photo',
  p_avallain: 'files.p_avallain',
  p_hoot: 'files.p_hoot',
  p_loyalty: 'files.p_loyalty',
  p_listen: 'files.p_listen',
  p_friends: 'files.p_friends',
  p_spider: 'files.p_spider',
  p_tracker: 'files.p_tracker',
  p_ship: 'files.p_ship',
  p_bahamas: 'files.p_bahamas'
};

const STRUCTURE_INDEX = {
  resume: [
    { kind: 'class', name: 'Dubrounik', line: 5, icon: 'C' },
    { kind: 'method', name: 'about_me', line: 12, icon: 'm' },
    { kind: 'method', name: 'core_competencies', line: 22, icon: 'm' },
    { kind: 'method', name: 'current_positions', line: 33, icon: 'm' },
    { kind: 'method', name: 'hire!', line: 41, icon: 'm' }
  ],
  experience: [
    { kind: 'module', name: 'Experience', line: 3, icon: 'M' },
    { kind: 'const', name: 'ROLES', line: 4, icon: 'c' },
    { kind: 'method', name: 'total_years', line: 12, icon: 'm' },
    { kind: 'method', name: 'highlights', line: 16, icon: 'm' }
  ],
  projects: [
    { kind: 'class', name: 'Projects', line: 3, icon: 'C' },
    { kind: 'const', name: 'REGISTRY', line: 4, icon: 'c' },
    { kind: 'method', name: 'all', line: 8, icon: 'm' },
    { kind: 'method', name: 'count', line: 11, icon: 'm' }
  ],
  skills: [
    { kind: 'class', name: 'SkillsEngine', line: 3, icon: 'C' },
    { kind: 'method', name: 'evaluate', line: 8, icon: 'm' }
  ],
  gemfile: [{ kind: 'file', name: 'Gemfile', line: 1, icon: 'G' }],
  readme: [{ kind: 'file', name: 'README.md', line: 1, icon: 'R' }]
};

PROJECT_KEYS.forEach(slug => {
  const key = PROJECTS_DATA[slug].key;
  const name = PROJECTS_DATA[slug].en.name.replace(/[^a-zA-Z]/g, '') || 'Project';
  STRUCTURE_INDEX[key] = [
    { kind: 'class', name, line: 3, icon: 'C' },
    { kind: 'method', name: 'description', line: 7, icon: 'm' },
    { kind: 'method', name: 'achievements', line: 11, icon: 'm' }
  ];
});

const SEARCH_INDEX = [
  { q: 'ruby rails', file: 'resume', line: 5 },
  { q: 'avallain elearning sso saml oneroster', file: 'p_avallain', line: 7 },
  { q: 'hoot medical dicom', file: 'p_hoot', line: 7 },
  { q: 'loyaltyplus kubernetes microservices rails migration', file: 'p_loyalty', line: 7 },
  { q: 'listenloop auth0 okta ai team lead', file: 'p_listen', line: 7 },
  { q: 'friendsurance elasticsearch ocr insurance sidekiq', file: 'p_friends', line: 7 },
  { q: 'spiderdoor twilio self storage', file: 'p_spider', line: 7 },
  { q: 'tracker agile anadea', file: 'p_tracker', line: 7 },
  { q: 'shiphawk shipping elasticsearch', file: 'p_ship', line: 7 },
  { q: 'bahamas vacations booking hotels', file: 'p_bahamas', line: 7 },
  { q: 'postgresql redis sidekiq sqs', file: 'skills', line: 10 },
  { q: 'mentoring teaching pair programming', file: 'experience', line: 18 },
  { q: 'itechart team manager', file: 'experience', line: 5 },
  { q: 'the lessoner education', file: 'experience', line: 8 },
  { q: 'yanka kupala university', file: 'education', line: 4 },
  { q: 'aws docker kubernetes', file: 'skills', line: 12 },
  { q: 'ai copilot cursor', file: 'resume', line: 20 },
  { q: 'contact hire email linkedin', file: 'contact', line: 10 },
  { q: 'gemfile rails sidekiq', file: 'gemfile', line: 5 },
  { q: 'readme documentation', file: 'readme', line: 4 }
];
